### ISSUE TITLE
Deleting math folder

### ISSUE THREAD

**Issue by Rahilsiddique** [cdhiraj40/eduJam#35]
https://github.com/cdhiraj40/eduJam/tree/main/app/src/main/java/com/example/gdsc_hackathon/fragments/syllabus/fourth_sem/maths

**Comment by cdhiraj40** [comment]
Sorry @Rahilsiddique I forgot to tell you, you can delete all files in this folder excluding ``MathsTutorialFragment.kt``, please don't delete ``MathsTutorialFragment.kt``.

**Comment by Rahilsiddique** [comment]
sorry, I think the pr I just made rn dose not include the whole maths folder. No issue I will improvise it

**Comment by Rahilsiddique** [comment]
hey, I have just made an imporvised pr as mentioned by you,  please review it and let me know anything that can be improved, thanks
